apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lingooru-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: lingooru-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: lingooru
